In [3]:
import pandas as pd
import numpy as np

data = {
    "name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank"],
    "age": [25, 30, np.nan, 40, np.nan, 50],
    "city": ["Houston", "Chicago", "Chicago", "Houston", "Miami", "Miami"],
    "salary": [50000, 60000, 70000, 80000, 90000, 40000]
}

In [7]:
df = pd.DataFrame(data)

In [9]:
df.isnull()

    name    age   city  salary
0  False  False  False   False
1  False  False  False   False
2  False   True  False   False
3  False  False  False   False
4  False   True  False   False
5  False  False  False   False

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    6 non-null      object
 1   age     4 non-null      float64
 2   city    6 non-null      object
 3   salary  6 non-null      int64
dtypes: float64(1), int64(1), object(2)
memory usage: 324.0+ bytes

In [10]:
df.dropna()

    name   age     city  salary
0  Alice  25.0  Houston   50000
1    Bob  30.0  Chicago   60000
3  David  40.0  Houston   80000
5  Frank  50.0    Miami   40000

In [11]:
df

      name   age     city  salary
0    Alice  25.0  Houston   50000
1      Bob  30.0  Chicago   60000
2  Charlie   NaN  Chicago   70000
3    David  40.0  Houston   80000
4      Eve   NaN    Miami   90000
5    Frank  50.0    Miami   40000

In [12]:
df.drop_duplicates(inplace=True)

In [13]:
df.dropna(subset=['salary'])

      name   age     city  salary
0    Alice  25.0  Houston   50000
1      Bob  30.0  Chicago   60000
2  Charlie   NaN  Chicago   70000
3    David  40.0  Houston   80000
4      Eve   NaN    Miami   90000
5    Frank  50.0    Miami   40000

In [16]:
# Box Plot
data = {
    'student': ["Alice", "Bob", "Charlie", "Davide", "Eve", "Frank","Alice"],
    'marks': [85, 90, 83, 83, 83, 83, 76, 83]
}

In [ ]:
# Importing values
import pandas as pd
import numpy as np

In [ ]:
df.fillna(df['marks'].mean())

In [24]:
import numpy as np
import pandas as pd

data = {
    "name": ["Ram", "Shyam", "Hari", "Sita", "Gita"],
    "age": [20, np.nan, 22, np.nan, 24],
    "gender": ["M", "M", "M", "F", "F"],
    "city": ["Kathmandu", "Lalitpur", "Bhaktpur", "lalitpur", "Kathmandu"],
    "marks": [85, np.nan, 95, np.nan, 85]
}
df_names = pd.DataFrame(data)

In [17]:
# Null values, null values count, drop null rows, fill null value with 20, drop duplicates

import pandas as pd

# Example DataFrame with null values
data = {
    'A': [1, 2, None, 4],
    'B': [None, 2, 3, 4],
    'C': [1, None, None, 4]
}
df = pd.DataFrame(data)

In [18]:
# Check for null values (True/False mask)
print(df.isnull())

       A      B      C
0  False   True  False
1  False  False   True
2   True  False   True
3  False  False  False

In [19]:
# Count total null values in each column

print(df.isnull().sum())

A    1
B    1
C    2
dtype: int64

In [20]:
# Drop rows with any null values

df_dropped = df.dropna()
print(df_dropped)

     A    B    C
3  4.0  4.0  4.0

In [21]:
# Fill null values with 20

df_filled = df.fillna(20)
print(df_filled)

      A     B     C
0   1.0  20.0   1.0
1   2.0   2.0  20.0
2  20.0   3.0  20.0
3   4.0   4.0   4.0

In [25]:
# drop duplicates using for 
df_names.drop_duplicates(subset=["city", "marks"])

    name   age gender       city  marks
0    Ram  20.0      M  Kathmandu   85.0
1  Shyam   NaN      M   Lalitpur    NaN
2   Hari  22.0      M   Bhaktpur   95.0
3   Sita   NaN      F   lalitpur    NaN

In [23]:
df

     A    B    C
0  1.0  NaN  1.0
1  2.0  2.0  NaN
2  NaN  3.0  NaN
3  4.0  4.0  4.0

In [ ]:
# create 1d, 2d, 3d numpy array using the list

import numpy as np

# 1D list
list_1d = [1, 2, 3, 4, 5]
array_1d = np.array(list_1d)

print("1D Array:")
print(array_1d)

1D Array:
[1 2 3 4 5]

In [27]:
# 2D list (list of lists)
list_2d = [[1, 2, 3], [4, 5, 6]]
array_2d = np.array(list_2d)

print("\n2D Array:")
print(array_2d)

2D Array:
[[1 2 3]
 [4 5 6]]

In [28]:
# 3D list (list of lists of lists)
list_3d = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
array_3d = np.array(list_3d)

print("\n3D Array:")
print(array_3d)

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]

In [ ]:
# also apply operations such as mean, median, squareroot(sqrt)

# 1d mean, median squareroot(sqrt)

import numpy as np

list_1d = [1, 2, 3, 4, 5]
array_1d = np.array(list_1d)

print("1D Array:", array_1d)
print("Mean:", np.mean(array_1d))
print("Median:", np.median(array_1d))
print("Square Root:", np.sqrt(array_1d))

1D Array: [1 2 3 4 5]
Mean: 3.0
Median: 3.0
Square Root: [1.         1.41421356 1.73205081 2.         2.23606798]

In [ ]:
# 2d 1d mean, median squareroot(sqrt)

list_2d = [[1, 2, 3], [4, 5, 6]]
array_2d = np.array(list_2d)

print("\n2D Array:\n", array_2d)
print("Mean:", np.mean(array_2d))
print("Median:", np.median(array_2d))
print("Square Root:\n", np.sqrt(array_2d))

2D Array:
 [[1 2 3]
 [4 5 6]]
Mean: 3.5
Median: 3.5
Square Root:
 [[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]]

In [ ]:
# 3d 1d mean, median squareroot(sqrt)

list_3d = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]
array_3d = np.array(list_3d)

print("\n3D Array:\n", array_3d)
print("Mean:", np.mean(array_3d))
print("Median:", np.median(array_3d))
print("Square Root:\n", np.sqrt(array_3d))

3D Array:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Mean: 4.5
Median: 4.5
Square Root:
 [[[1.         1.41421356]
  [1.73205081 2.        ]]

 [[2.23606798 2.44948974]
  [2.64575131 2.82842712]]]