In [1]:
import numpy as np
import pandas as pd

In [2]:
# 1. EMPLOYEES Table
employees_data = {
    'employee_id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    'first_name': ['John', 'Sarah', 'Michael', 'Emma', 'David', 'Lisa', 'Robert', 'Anna', 'James', 'Maria', 'Kevin', 'Laura', 'Mark', 'Sophie', 'Alex'],
    'last_name': ['Smith', 'Johnson', 'Brown', 'Davis', 'Wilson', 'Miller', 'Jones', 'Garcia', 'Martinez', 'Rodriguez', 'Lee', 'Walker', 'Hall', 'Allen', 'Young'],
    'department_id': [1, 2, 1, 3, 2, 1, 4, 3, 2, 1, 4, 3, 2, 1, 5],
    'position': ['Manager', 'Analyst', 'Developer', 'Designer', 'Manager', 'Developer', 'Analyst', 'Designer', 'Developer', 'Manager', 'Analyst', 'Designer', 'Analyst', 'Developer', 'Manager'],
    'salary': [75000, 55000, 68000, 62000, 80000, 70000, 52000, 58000, 65000, 85000, 50000, 60000, 56000, 72000, 90000],
    'hire_date': ['2019-03-15', '2020-07-22', '2021-01-10', '2020-11-08', '2018-05-30', '2021-03-25', '2022-01-15', '2019-09-12', '2021-08-20', '2017-12-05', '2022-04-10', '2020-02-18', '2021-11-30', '2020-06-14', '2023-01-08'],
    'email': ['john.smith@company.com', 'sarah.johnson@company.com', 'michael.brown@company.com', 'emma.davis@company.com', 'david.wilson@company.com', 'lisa.miller@company.com', 'robert.jones@company.com', 'anna.garcia@company.com', 'james.martinez@company.com', 'maria.rodriguez@company.com', 'kevin.lee@company.com', 'laura.walker@company.com', 'mark.hall@company.com', 'sophie.allen@company.com', 'alex.young@company.com'],
    'phone': ['555-0101', '555-0102', '555-0103', '555-0104', '555-0105', '555-0106', '555-0107', '555-0108', '555-0109', '555-0110', '555-0111', '555-0112', '555-0113', '555-0114', '555-0115']
}

# 2. DEPARTMENTS Table
departments_data = {
    'department_id': [1, 2, 3, 4, 5, 6],
    'department_name': ['Engineering', 'Sales', 'Design', 'Marketing', 'Finance', 'HR'],
    'manager_id': [10, 5, 4, 7, 15, None],
    'budget': [500000, 300000, 200000, 250000, 180000, 150000],
    'location': ['New York', 'Chicago', 'San Francisco', 'Los Angeles', 'Boston', 'Seattle']
}

# 3. PROJECTS Table
projects_data = {
    'project_id': [101, 102, 103, 104, 105, 106, 107],
    'project_name': ['Website Redesign', 'Mobile App', 'Data Analytics', 'Marketing Campaign', 'ERP System', 'Customer Portal', 'AI Integration'],
    'department_id': [1, 1, 2, 4, 5, 1, 1],
    'start_date': ['2023-01-15', '2023-03-01', '2023-02-10', '2023-04-05', '2022-11-20', '2023-05-12', '2023-06-01'],
    'end_date': ['2023-06-30', '2023-08-15', '2023-07-20', '2023-09-30', '2024-02-28', '2023-10-15', '2024-01-31'],
    'budget': [150000, 200000, 100000, 80000, 300000, 120000, 250000],
    'status': ['Completed', 'In Progress', 'Completed', 'In Progress', 'In Progress', 'Planning', 'Planning']
}
employee_projects_data = {
    'employee_id': [1, 2, 3, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 1, 2, 5],
    'project_id': [101, 102, 101, 102, 103, 104, 101, 102, 103, 101, 105, 104, 103, 102, 101, 105, 106, 107, 107],
    'role': ['Lead', 'Developer', 'Developer', 'Tester', 'Analyst', 'Lead', 'Developer', 'Analyst', 'Designer', 'Developer', 'Lead', 'Analyst', 'Designer', 'Analyst', 'Developer', 'Lead', 'Manager', 'Developer', 'Manager'],
    'hours_allocated': [40, 35, 30, 20, 40, 40, 25, 30, 35, 20, 40, 25, 30, 20, 15, 40, 30, 35, 25]
}

In [3]:
employees_data_df = pd.DataFrame(employees_data)
departments_data_df = pd.DataFrame(departments_data)
projects_data_df = pd.DataFrame(projects_data)
employee_projects_data_df = pd.DataFrame(employee_projects_data)

In [4]:
employees_data_df

,employee_id,first_name,last_name,department_id,position,salary,hire_date,email,phone
0,1,John,Smith,1,Manager,75000,2019-03-15,john.smith@company.com,555-0101
1,2,Sarah,Johnson,2,Analyst,55000,2020-07-22,sarah.johnson@company.com,555-0102
2,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103
3,4,Emma,Davis,3,Designer,62000,2020-11-08,emma.davis@company.com,555-0104
4,5,David,Wilson,2,Manager,80000,2018-05-30,david.wilson@company.com,555-0105
5,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106
6,7,Robert,Jones,4,Analyst,52000,2022-01-15,robert.jones@company.com,555-0107
7,8,Anna,Garcia,3,Designer,58000,2019-09-12,anna.garcia@company.com,555-0108
8,9,James,Martinez,2,Developer,65000,2021-08-20,james.martinez@company.com,555-0109
9,10,Maria,Rodriguez,1,Manager,85000,2017-12-05,maria.rodriguez@company.com,555-0110
10,11,Kevin,Lee,4,Analyst,50000,2022-04-10,kevin.lee@company.com,555-0111
11,12,Laura,Walker,3,Designer,60000,2020-02-18,laura.walker@company.com,555-0112
12,13,Mark,Hall,2,Analyst,56000,2021-11-30,mark.hall@company.com,555-0113
13,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114
14,15,Alex,Young,5,Manager,90000,2023-01-08,alex.young@company.com,555-0115

In [15]:
employees_data_df[['first_name','last_name']]

   first_name  last_name
0        John      Smith
1       Sarah    Johnson
2     Michael      Brown
3        Emma      Davis
4       David     Wilson
5        Lisa     Miller
6      Robert      Jones
7        Anna     Garcia
8       James   Martinez
9       Maria  Rodriguez
10      Kevin        Lee
11      Laura     Walker
12       Mark       Hall
13     Sophie      Allen
14       Alex      Young

In [8]:
employees_data_df['department_id'].unique()

array([1, 2, 3, 4, 5])

In [5]:
employees_data_df.rename(columns={'first_name': 'First_Name'})

,employee_id,First_Name,last_name,department_id,position,salary,hire_date,email,phone
0,1,John,Smith,1,Manager,75000,2019-03-15,john.smith@company.com,555-0101
1,2,Sarah,Johnson,2,Analyst,55000,2020-07-22,sarah.johnson@company.com,555-0102
2,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103
3,4,Emma,Davis,3,Designer,62000,2020-11-08,emma.davis@company.com,555-0104
4,5,David,Wilson,2,Manager,80000,2018-05-30,david.wilson@company.com,555-0105
5,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106
6,7,Robert,Jones,4,Analyst,52000,2022-01-15,robert.jones@company.com,555-0107
7,8,Anna,Garcia,3,Designer,58000,2019-09-12,anna.garcia@company.com,555-0108
8,9,James,Martinez,2,Developer,65000,2021-08-20,james.martinez@company.com,555-0109
9,10,Maria,Rodriguez,1,Manager,85000,2017-12-05,maria.rodriguez@company.com,555-0110
10,11,Kevin,Lee,4,Analyst,50000,2022-04-10,kevin.lee@company.com,555-0111
11,12,Laura,Walker,3,Designer,60000,2020-02-18,laura.walker@company.com,555-0112
12,13,Mark,Hall,2,Analyst,56000,2021-11-30,mark.hall@company.com,555-0113
13,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114
14,15,Alex,Young,5,Manager,90000,2023-01-08,alex.young@company.com,555-0115

In [10]:
employees_data_df[employees_data_df['salary'] > 50000]

,employee_id,first_name,last_name,department_id,position,salary,hire_date,email,phone
0,1,John,Smith,1,Manager,75000,2019-03-15,john.smith@company.com,555-0101
1,2,Sarah,Johnson,2,Analyst,55000,2020-07-22,sarah.johnson@company.com,555-0102
2,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103
3,4,Emma,Davis,3,Designer,62000,2020-11-08,emma.davis@company.com,555-0104
4,5,David,Wilson,2,Manager,80000,2018-05-30,david.wilson@company.com,555-0105
5,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106
6,7,Robert,Jones,4,Analyst,52000,2022-01-15,robert.jones@company.com,555-0107
7,8,Anna,Garcia,3,Designer,58000,2019-09-12,anna.garcia@company.com,555-0108
8,9,James,Martinez,2,Developer,65000,2021-08-20,james.martinez@company.com,555-0109
9,10,Maria,Rodriguez,1,Manager,85000,2017-12-05,maria.rodriguez@company.com,555-0110
11,12,Laura,Walker,3,Designer,60000,2020-02-18,laura.walker@company.com,555-0112
12,13,Mark,Hall,2,Analyst,56000,2021-11-30,mark.hall@company.com,555-0113
13,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114
14,15,Alex,Young,5,Manager,90000,2023-01-08,alex.young@company.com,555-0115

In [13]:
employees_data_df[employees_data_df['position']=='Developer']

,employee_id,first_name,last_name,department_id,position,salary,hire_date,email,phone
2,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103
5,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106
8,9,James,Martinez,2,Developer,65000,2021-08-20,james.martinez@company.com,555-0109
13,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114

In [21]:
employees_data_df['hire_date'] = pd.to_datetime(employees_data_df['hire_date'])

In [22]:
employees_data_df[employees_data_df['hire_date'] > '2020-01-01']

,employee_id,first_name,last_name,department_id,position,salary,hire_date,email,phone,hire_data
1,2,Sarah,Johnson,2,Analyst,55000,2020-07-22,sarah.johnson@company.com,555-0102,2020-07-22
2,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103,2021-01-10
3,4,Emma,Davis,3,Designer,62000,2020-11-08,emma.davis@company.com,555-0104,2020-11-08
5,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106,2021-03-25
6,7,Robert,Jones,4,Analyst,52000,2022-01-15,robert.jones@company.com,555-0107,2022-01-15
8,9,James,Martinez,2,Developer,65000,2021-08-20,james.martinez@company.com,555-0109,2021-08-20
10,11,Kevin,Lee,4,Analyst,50000,2022-04-10,kevin.lee@company.com,555-0111,2022-04-10
11,12,Laura,Walker,3,Designer,60000,2020-02-18,laura.walker@company.com,555-0112,2020-02-18
12,13,Mark,Hall,2,Analyst,56000,2021-11-30,mark.hall@company.com,555-0113,2021-11-30
13,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114,2020-06-14
14,15,Alex,Young,5,Manager,90000,2023-01-08,alex.young@company.com,555-0115,2023-01-08

In [18]:
employees_data_df[(employees_data_df['position']=='Developer') & (employees_data_df['salary'] > 60000)]

,employee_id,first_name,last_name,department_id,position,salary,hire_date,email,phone,hire_data
2,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103,2021-01-10
5,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106,2021-03-25
8,9,James,Martinez,2,Developer,65000,2021-08-20,james.martinez@company.com,555-0109,2021-08-20
13,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114,2020-06-14

In [19]:
employees_data_df[employees_data_df['first_name'].str.startswith('Mich')]

,employee_id,first_name,last_name,department_id,position,salary,hire_date,email,phone,hire_data
2,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103,2021-01-10

In [23]:
employees_data_df[employees_data_df['position'].isin(['Developer', 'Designer'])]

,employee_id,first_name,last_name,department_id,position,salary,hire_date,email,phone,hire_data
2,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103,2021-01-10
3,4,Emma,Davis,3,Designer,62000,2020-11-08,emma.davis@company.com,555-0104,2020-11-08
5,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106,2021-03-25
7,8,Anna,Garcia,3,Designer,58000,2019-09-12,anna.garcia@company.com,555-0108,2019-09-12
8,9,James,Martinez,2,Developer,65000,2021-08-20,james.martinez@company.com,555-0109,2021-08-20
11,12,Laura,Walker,3,Designer,60000,2020-02-18,laura.walker@company.com,555-0112,2020-02-18
13,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114,2020-06-14

In [24]:
# Group by statement

employees_data_df.groupby('department_id').size().reset_index(name='employee_count')

   department_id  employee_count
0              1               5
1              2               4
2              3               3
3              4               2
4              5               1

In [25]:
employees_data_df.groupby('position').size().reset_index(name='employee_count')

    position  employee_count
0    Analyst               4
1   Designer               3
2  Developer               4
3    Manager               4

In [ ]:
# Mean

employees_data_df.groupby('department_id')['salary'].mean().reset_index()

   department_id   salary
0              1  74000.0
1              2  64000.0
2              3  60000.0
3              4  51000.0
4              5  90000.0

In [28]:
employees_data_df.groupby(['department_id', 'position'])['salary'].mean().reset_index()

   department_id   position   salary
0              1  Developer  70000.0
1              1    Manager  80000.0
2              2    Analyst  55500.0
3              2  Developer  65000.0
4              2    Manager  80000.0
5              3   Designer  60000.0
6              4    Analyst  51000.0
7              5    Manager  90000.0

In [27]:
# Order by

employees_data_df.sort_values(by='first_name', ascending=True)

,employee_id,first_name,last_name,department_id,position,salary,hire_date,email,phone,hire_data
14,15,Alex,Young,5,Manager,90000,2023-01-08,alex.young@company.com,555-0115,2023-01-08
7,8,Anna,Garcia,3,Designer,58000,2019-09-12,anna.garcia@company.com,555-0108,2019-09-12
4,5,David,Wilson,2,Manager,80000,2018-05-30,david.wilson@company.com,555-0105,2018-05-30
3,4,Emma,Davis,3,Designer,62000,2020-11-08,emma.davis@company.com,555-0104,2020-11-08
8,9,James,Martinez,2,Developer,65000,2021-08-20,james.martinez@company.com,555-0109,2021-08-20
0,1,John,Smith,1,Manager,75000,2019-03-15,john.smith@company.com,555-0101,2019-03-15
10,11,Kevin,Lee,4,Analyst,50000,2022-04-10,kevin.lee@company.com,555-0111,2022-04-10
11,12,Laura,Walker,3,Designer,60000,2020-02-18,laura.walker@company.com,555-0112,2020-02-18
5,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106,2021-03-25
9,10,Maria,Rodriguez,1,Manager,85000,2017-12-05,maria.rodriguez@company.com,555-0110,2017-12-05
12,13,Mark,Hall,2,Analyst,56000,2021-11-30,mark.hall@company.com,555-0113,2021-11-30
2,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103,2021-01-10
6,7,Robert,Jones,4,Analyst,52000,2022-01-15,robert.jones@company.com,555-0107,2022-01-15
1,2,Sarah,Johnson,2,Analyst,55000,2020-07-22,sarah.johnson@company.com,555-0102,2020-07-22
13,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114,2020-06-14

In [29]:
employees_data_df.sort_values(by=['first_name','salary'], ascending=[True,False])

,employee_id,first_name,last_name,department_id,position,salary,hire_date,email,phone,hire_data
14,15,Alex,Young,5,Manager,90000,2023-01-08,alex.young@company.com,555-0115,2023-01-08
7,8,Anna,Garcia,3,Designer,58000,2019-09-12,anna.garcia@company.com,555-0108,2019-09-12
4,5,David,Wilson,2,Manager,80000,2018-05-30,david.wilson@company.com,555-0105,2018-05-30
3,4,Emma,Davis,3,Designer,62000,2020-11-08,emma.davis@company.com,555-0104,2020-11-08
8,9,James,Martinez,2,Developer,65000,2021-08-20,james.martinez@company.com,555-0109,2021-08-20
0,1,John,Smith,1,Manager,75000,2019-03-15,john.smith@company.com,555-0101,2019-03-15
10,11,Kevin,Lee,4,Analyst,50000,2022-04-10,kevin.lee@company.com,555-0111,2022-04-10
11,12,Laura,Walker,3,Designer,60000,2020-02-18,laura.walker@company.com,555-0112,2020-02-18
5,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106,2021-03-25
9,10,Maria,Rodriguez,1,Manager,85000,2017-12-05,maria.rodriguez@company.com,555-0110,2017-12-05
12,13,Mark,Hall,2,Analyst,56000,2021-11-30,mark.hall@company.com,555-0113,2021-11-30
2,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103,2021-01-10
6,7,Robert,Jones,4,Analyst,52000,2022-01-15,robert.jones@company.com,555-0107,2022-01-15
1,2,Sarah,Johnson,2,Analyst,55000,2020-07-22,sarah.johnson@company.com,555-0102,2020-07-22
13,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114,2020-06-14

In [30]:
employees_data_df.sort_values(by=employees_data_df.columns[2])

,employee_id,first_name,last_name,department_id,position,salary,hire_date,email,phone,hire_data
13,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114,2020-06-14
2,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103,2021-01-10
3,4,Emma,Davis,3,Designer,62000,2020-11-08,emma.davis@company.com,555-0104,2020-11-08
7,8,Anna,Garcia,3,Designer,58000,2019-09-12,anna.garcia@company.com,555-0108,2019-09-12
12,13,Mark,Hall,2,Analyst,56000,2021-11-30,mark.hall@company.com,555-0113,2021-11-30
1,2,Sarah,Johnson,2,Analyst,55000,2020-07-22,sarah.johnson@company.com,555-0102,2020-07-22
6,7,Robert,Jones,4,Analyst,52000,2022-01-15,robert.jones@company.com,555-0107,2022-01-15
10,11,Kevin,Lee,4,Analyst,50000,2022-04-10,kevin.lee@company.com,555-0111,2022-04-10
8,9,James,Martinez,2,Developer,65000,2021-08-20,james.martinez@company.com,555-0109,2021-08-20
5,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106,2021-03-25
9,10,Maria,Rodriguez,1,Manager,85000,2017-12-05,maria.rodriguez@company.com,555-0110,2017-12-05
0,1,John,Smith,1,Manager,75000,2019-03-15,john.smith@company.com,555-0101,2019-03-15
11,12,Laura,Walker,3,Designer,60000,2020-02-18,laura.walker@company.com,555-0112,2020-02-18
4,5,David,Wilson,2,Manager,80000,2018-05-30,david.wilson@company.com,555-0105,2018-05-30
14,15,Alex,Young,5,Manager,90000,2023-01-08,alex.young@company.com,555-0115,2023-01-08

In [31]:
# Joins

# Inner Join

merged_df = pd.merge(employees_data_df, departments_data_df, on='department_id', how='inner')

In [32]:
merged_df

,employee_id,first_name,last_name,department_id,position,salary,hire_date,email,phone,hire_data,department_name,manager_id,budget,location
0,1,John,Smith,1,Manager,75000,2019-03-15,john.smith@company.com,555-0101,2019-03-15,Engineering,10.0,500000,New York
1,2,Sarah,Johnson,2,Analyst,55000,2020-07-22,sarah.johnson@company.com,555-0102,2020-07-22,Sales,5.0,300000,Chicago
2,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103,2021-01-10,Engineering,10.0,500000,New York
3,4,Emma,Davis,3,Designer,62000,2020-11-08,emma.davis@company.com,555-0104,2020-11-08,Design,4.0,200000,San Francisco
4,5,David,Wilson,2,Manager,80000,2018-05-30,david.wilson@company.com,555-0105,2018-05-30,Sales,5.0,300000,Chicago
5,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106,2021-03-25,Engineering,10.0,500000,New York
6,7,Robert,Jones,4,Analyst,52000,2022-01-15,robert.jones@company.com,555-0107,2022-01-15,Marketing,7.0,250000,Los Angeles
7,8,Anna,Garcia,3,Designer,58000,2019-09-12,anna.garcia@company.com,555-0108,2019-09-12,Design,4.0,200000,San Francisco
8,9,James,Martinez,2,Developer,65000,2021-08-20,james.martinez@company.com,555-0109,2021-08-20,Sales,5.0,300000,Chicago
9,10,Maria,Rodriguez,1,Manager,85000,2017-12-05,maria.rodriguez@company.com,555-0110,2017-12-05,Engineering,10.0,500000,New York
10,11,Kevin,Lee,4,Analyst,50000,2022-04-10,kevin.lee@company.com,555-0111,2022-04-10,Marketing,7.0,250000,Los Angeles
11,12,Laura,Walker,3,Designer,60000,2020-02-18,laura.walker@company.com,555-0112,2020-02-18,Design,4.0,200000,San Francisco
12,13,Mark,Hall,2,Analyst,56000,2021-11-30,mark.hall@company.com,555-0113,2021-11-30,Sales,5.0,300000,Chicago
13,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114,2020-06-14,Engineering,10.0,500000,New York
14,15,Alex,Young,5,Manager,90000,2023-01-08,alex.young@company.com,555-0115,2023-01-08,Finance,15.0,180000,Boston

In [40]:
employees_data_df.columns

Index(['employee_id', 'first_name', 'last_name', 'department_id', 'position',
       'salary', 'hire_date', 'email', 'phone', 'hire_data'],
      dtype='object')

In [41]:
departments_data_df.columns

Index(['department_id', 'department_name', 'manager_id', 'budget', 'location'], dtype='object')

In [42]:
employees_data_df.merge(departments_data_df, on='department_id', how='outer')

,employee_id,first_name,last_name,department_id,position,salary,hire_date,email,phone,hire_data,department_name,manager_id,budget,location
0,1.0,John,Smith,1,Manager,75000.0,2019-03-15,john.smith@company.com,555-0101,2019-03-15,Engineering,10.0,500000,New York
1,3.0,Michael,Brown,1,Developer,68000.0,2021-01-10,michael.brown@company.com,555-0103,2021-01-10,Engineering,10.0,500000,New York
2,6.0,Lisa,Miller,1,Developer,70000.0,2021-03-25,lisa.miller@company.com,555-0106,2021-03-25,Engineering,10.0,500000,New York
3,10.0,Maria,Rodriguez,1,Manager,85000.0,2017-12-05,maria.rodriguez@company.com,555-0110,2017-12-05,Engineering,10.0,500000,New York
4,14.0,Sophie,Allen,1,Developer,72000.0,2020-06-14,sophie.allen@company.com,555-0114,2020-06-14,Engineering,10.0,500000,New York
5,2.0,Sarah,Johnson,2,Analyst,55000.0,2020-07-22,sarah.johnson@company.com,555-0102,2020-07-22,Sales,5.0,300000,Chicago
6,5.0,David,Wilson,2,Manager,80000.0,2018-05-30,david.wilson@company.com,555-0105,2018-05-30,Sales,5.0,300000,Chicago
7,9.0,James,Martinez,2,Developer,65000.0,2021-08-20,james.martinez@company.com,555-0109,2021-08-20,Sales,5.0,300000,Chicago
8,13.0,Mark,Hall,2,Analyst,56000.0,2021-11-30,mark.hall@company.com,555-0113,2021-11-30,Sales,5.0,300000,Chicago
9,4.0,Emma,Davis,3,Designer,62000.0,2020-11-08,emma.davis@company.com,555-0104,2020-11-08,Design,4.0,200000,San Francisco
10,8.0,Anna,Garcia,3,Designer,58000.0,2019-09-12,anna.garcia@company.com,555-0108,2019-09-12,Design,4.0,200000,San Francisco
11,12.0,Laura,Walker,3,Designer,60000.0,2020-02-18,laura.walker@company.com,555-0112,2020-02-18,Design,4.0,200000,San Francisco
12,7.0,Robert,Jones,4,Analyst,52000.0,2022-01-15,robert.jones@company.com,555-0107,2022-01-15,Marketing,7.0,250000,Los Angeles
13,11.0,Kevin,Lee,4,Analyst,50000.0,2022-04-10,kevin.lee@company.com,555-0111,2022-04-10,Marketing,7.0,250000,Los Angeles
14,15.0,Alex,Young,5,Manager,90000.0,2023-01-08,alex.young@company.com,555-0115,2023-01-08,Finance,15.0,180000,Boston
15,NaN,NaN,NaN,6,NaN,NaN,NaT,NaN,NaN,NaT,HR,NaN,150000,Seattle

In [46]:
employees_data_df.merge(departments_data_df, on='department_id', how='left')

,employee_id,first_name,last_name,department_id,position,salary,hire_date,email,phone,hire_data,department_name,manager_id,budget,location
0,1,John,Smith,1,Manager,75000,2019-03-15,john.smith@company.com,555-0101,2019-03-15,Engineering,10.0,500000,New York
1,2,Sarah,Johnson,2,Analyst,55000,2020-07-22,sarah.johnson@company.com,555-0102,2020-07-22,Sales,5.0,300000,Chicago
2,3,Michael,Brown,1,Developer,68000,2021-01-10,michael.brown@company.com,555-0103,2021-01-10,Engineering,10.0,500000,New York
3,4,Emma,Davis,3,Designer,62000,2020-11-08,emma.davis@company.com,555-0104,2020-11-08,Design,4.0,200000,San Francisco
4,5,David,Wilson,2,Manager,80000,2018-05-30,david.wilson@company.com,555-0105,2018-05-30,Sales,5.0,300000,Chicago
5,6,Lisa,Miller,1,Developer,70000,2021-03-25,lisa.miller@company.com,555-0106,2021-03-25,Engineering,10.0,500000,New York
6,7,Robert,Jones,4,Analyst,52000,2022-01-15,robert.jones@company.com,555-0107,2022-01-15,Marketing,7.0,250000,Los Angeles
7,8,Anna,Garcia,3,Designer,58000,2019-09-12,anna.garcia@company.com,555-0108,2019-09-12,Design,4.0,200000,San Francisco
8,9,James,Martinez,2,Developer,65000,2021-08-20,james.martinez@company.com,555-0109,2021-08-20,Sales,5.0,300000,Chicago
9,10,Maria,Rodriguez,1,Manager,85000,2017-12-05,maria.rodriguez@company.com,555-0110,2017-12-05,Engineering,10.0,500000,New York
10,11,Kevin,Lee,4,Analyst,50000,2022-04-10,kevin.lee@company.com,555-0111,2022-04-10,Marketing,7.0,250000,Los Angeles
11,12,Laura,Walker,3,Designer,60000,2020-02-18,laura.walker@company.com,555-0112,2020-02-18,Design,4.0,200000,San Francisco
12,13,Mark,Hall,2,Analyst,56000,2021-11-30,mark.hall@company.com,555-0113,2021-11-30,Sales,5.0,300000,Chicago
13,14,Sophie,Allen,1,Developer,72000,2020-06-14,sophie.allen@company.com,555-0114,2020-06-14,Engineering,10.0,500000,New York
14,15,Alex,Young,5,Manager,90000,2023-01-08,alex.young@company.com,555-0115,2023-01-08,Finance,15.0,180000,Boston

In [47]:
employees_data_df.merge(departments_data_df, on='department_id', how='right')

,employee_id,first_name,last_name,department_id,position,salary,hire_date,email,phone,hire_data,department_name,manager_id,budget,location
0,1.0,John,Smith,1,Manager,75000.0,2019-03-15,john.smith@company.com,555-0101,2019-03-15,Engineering,10.0,500000,New York
1,3.0,Michael,Brown,1,Developer,68000.0,2021-01-10,michael.brown@company.com,555-0103,2021-01-10,Engineering,10.0,500000,New York
2,6.0,Lisa,Miller,1,Developer,70000.0,2021-03-25,lisa.miller@company.com,555-0106,2021-03-25,Engineering,10.0,500000,New York
3,10.0,Maria,Rodriguez,1,Manager,85000.0,2017-12-05,maria.rodriguez@company.com,555-0110,2017-12-05,Engineering,10.0,500000,New York
4,14.0,Sophie,Allen,1,Developer,72000.0,2020-06-14,sophie.allen@company.com,555-0114,2020-06-14,Engineering,10.0,500000,New York
5,2.0,Sarah,Johnson,2,Analyst,55000.0,2020-07-22,sarah.johnson@company.com,555-0102,2020-07-22,Sales,5.0,300000,Chicago
6,5.0,David,Wilson,2,Manager,80000.0,2018-05-30,david.wilson@company.com,555-0105,2018-05-30,Sales,5.0,300000,Chicago
7,9.0,James,Martinez,2,Developer,65000.0,2021-08-20,james.martinez@company.com,555-0109,2021-08-20,Sales,5.0,300000,Chicago
8,13.0,Mark,Hall,2,Analyst,56000.0,2021-11-30,mark.hall@company.com,555-0113,2021-11-30,Sales,5.0,300000,Chicago
9,4.0,Emma,Davis,3,Designer,62000.0,2020-11-08,emma.davis@company.com,555-0104,2020-11-08,Design,4.0,200000,San Francisco
10,8.0,Anna,Garcia,3,Designer,58000.0,2019-09-12,anna.garcia@company.com,555-0108,2019-09-12,Design,4.0,200000,San Francisco
11,12.0,Laura,Walker,3,Designer,60000.0,2020-02-18,laura.walker@company.com,555-0112,2020-02-18,Design,4.0,200000,San Francisco
12,7.0,Robert,Jones,4,Analyst,52000.0,2022-01-15,robert.jones@company.com,555-0107,2022-01-15,Marketing,7.0,250000,Los Angeles
13,11.0,Kevin,Lee,4,Analyst,50000.0,2022-04-10,kevin.lee@company.com,555-0111,2022-04-10,Marketing,7.0,250000,Los Angeles
14,15.0,Alex,Young,5,Manager,90000.0,2023-01-08,alex.young@company.com,555-0115,2023-01-08,Finance,15.0,180000,Boston
15,NaN,NaN,NaN,6,NaN,NaN,NaT,NaN,NaN,NaT,HR,NaN,150000,Seattle

In [45]:
employees_data_df.columns

Index(['employee_id', 'first_name', 'last_name', 'department_id', 'position',
       'salary', 'hire_date', 'email', 'phone', 'hire_data'],
      dtype='object')

In [51]:
# projects_data_df, employees_data_df join

employees_data_df.merge(departments_data_df, on='department_id', how='right')

,employee_id,first_name,last_name,department_id,position,salary,hire_date,email,phone,hire_data,department_name,manager_id,budget,location
0,1.0,John,Smith,1,Manager,75000.0,2019-03-15,john.smith@company.com,555-0101,2019-03-15,Engineering,10.0,500000,New York
1,3.0,Michael,Brown,1,Developer,68000.0,2021-01-10,michael.brown@company.com,555-0103,2021-01-10,Engineering,10.0,500000,New York
2,6.0,Lisa,Miller,1,Developer,70000.0,2021-03-25,lisa.miller@company.com,555-0106,2021-03-25,Engineering,10.0,500000,New York
3,10.0,Maria,Rodriguez,1,Manager,85000.0,2017-12-05,maria.rodriguez@company.com,555-0110,2017-12-05,Engineering,10.0,500000,New York
4,14.0,Sophie,Allen,1,Developer,72000.0,2020-06-14,sophie.allen@company.com,555-0114,2020-06-14,Engineering,10.0,500000,New York
5,2.0,Sarah,Johnson,2,Analyst,55000.0,2020-07-22,sarah.johnson@company.com,555-0102,2020-07-22,Sales,5.0,300000,Chicago
6,5.0,David,Wilson,2,Manager,80000.0,2018-05-30,david.wilson@company.com,555-0105,2018-05-30,Sales,5.0,300000,Chicago
7,9.0,James,Martinez,2,Developer,65000.0,2021-08-20,james.martinez@company.com,555-0109,2021-08-20,Sales,5.0,300000,Chicago
8,13.0,Mark,Hall,2,Analyst,56000.0,2021-11-30,mark.hall@company.com,555-0113,2021-11-30,Sales,5.0,300000,Chicago
9,4.0,Emma,Davis,3,Designer,62000.0,2020-11-08,emma.davis@company.com,555-0104,2020-11-08,Design,4.0,200000,San Francisco
10,8.0,Anna,Garcia,3,Designer,58000.0,2019-09-12,anna.garcia@company.com,555-0108,2019-09-12,Design,4.0,200000,San Francisco
11,12.0,Laura,Walker,3,Designer,60000.0,2020-02-18,laura.walker@company.com,555-0112,2020-02-18,Design,4.0,200000,San Francisco
12,7.0,Robert,Jones,4,Analyst,52000.0,2022-01-15,robert.jones@company.com,555-0107,2022-01-15,Marketing,7.0,250000,Los Angeles
13,11.0,Kevin,Lee,4,Analyst,50000.0,2022-04-10,kevin.lee@company.com,555-0111,2022-04-10,Marketing,7.0,250000,Los Angeles
14,15.0,Alex,Young,5,Manager,90000.0,2023-01-08,alex.young@company.com,555-0115,2023-01-08,Finance,15.0,180000,Boston
15,NaN,NaN,NaN,6,NaN,NaN,NaT,NaN,NaN,NaT,HR,NaN,150000,Seattle