In [2]:
# Area of Circle
pi = 3.14
radius = float(input('Enter the radius'))
area = pi*radius*radius

print('Area of the Circle is', area)

Area of the Circle is 78.5

In [3]:
a = [1, 2, 3, 4]

In [4]:
a[-1]

4

In [5]:
# Mean
# X = sumf(x)/N

sum = 0
for num in a:
    sum = sum + sum

In [1]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]

In [7]:
arr_2d = np.array([[1, 2, 3],[4, 5, 6]])

In [8]:
print(arr_2d)

[[1 2 3]
 [4 5 6]]

In [14]:
arr_3d = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [15]:
arr_3d.shape

(1, 3, 3)

In [16]:
arr_3d.ndim

3

In [17]:
arr

array([1, 2, 3, 4, 5])

In [19]:
arr = np.zeros((3,3))

In [20]:
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [23]:
arr = np.arange(2,10,2)

In [24]:
import numpy as np
arr = np.linspace(1, 10, 4)
print(arr)
print(arr.shape)
print(arr.ndim)
print(arr.size)
print(arr.dtype)
print(arr.itemsize)

[ 1.  4.  7. 10.]
(4,)
1
4
float64
8

In [25]:
arr = np.linspace(1,2,4)

In [26]:
arr

array([1.        , 1.33333333, 1.66666667, 2.        ])

In [31]:
arr = np.array([1,2.5,3,4])

In [32]:
arr.dtype

dtype('float64')

In [33]:
arr = np.array([1,'str',3,4])

In [34]:
print(arr)

['1' 'str' '3' '4']

In [38]:
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]

In [41]:
slice.start

In [46]:
print(arr_2d[1][1])

5

In [48]:
import numpy as np
arr_1d = np.array([1,2,3,4,5])
arr_1d[1:3]

array([2, 3])

In [49]:
arr = np.array([2,4,5,6])

np.where(arr>4,'Greater than 4','Less then 4')

array(['Less then 4', 'Less then 4', 'Greater than 4', 'Greater than 4'],
      dtype='<U14')

In [ ]:
arr = np.array([2,4,5,8])

In [1]:
import pandas as pd

In [2]:
num_list = [1,2,3,4,5]

series = pd.Series(num_list)

print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [3]:
import numpy as np

In [4]:
arr = np.array(num_list)
print(arr)

[1 2 3 4 5]

In [5]:
import pandas as pd

In [7]:
arr = np.array([1,2,3,4,5])

series = pd.Series(arr, index=['I', 'II', 'III', 'IV', 'V'])

print(series)

I      1
II     2
III    3
IV     4
V      5
dtype: int64

In [8]:
series_1 = pd.Series([1,2,3,4,5])
series_2 = pd.Series([6, 7, 8, 9, 10])

In [9]:
sum_series = series_1 + series_2

In [10]:
sum_series

0     7
1     9
2    11
3    13
4    15
dtype: int64

In [11]:
sub_series = series_1 - series_2

In [12]:
sub_series

0   -5
1   -5
2   -5
3   -5
4   -5
dtype: int64

In [ ]:
#filtering using or operator
sum_series[(sum_series > 10) | (sum_series < 15)]

0     7
1     9
2    11
3    13
4    15
dtype: int64

In [15]:
# data frames
data = {
    "Name":["Arun", "Bob", "CharLie", "David", "Eva"],
    "Age":[25,38,35,40,45],
    "City":["New York", "Lost Angeles", "Chicago","Houston", "Miani"]
}

df = pd.DataFrame(data)
print(data)

{'Name': ['Arun', 'Bob', 'CharLie', 'David', 'Eva'], 'Age': [25, 38, 35, 40, 45], 'City': ['New York', 'Lost Angeles', 'Chicago', 'Houston', 'Miani']}

In [17]:
df.head(3)

      Name  Age          City
0     Arun   25      New York
1      Bob   38  Lost Angeles
2  CharLie   35       Chicago

In [18]:
df.tail(3)

      Name  Age     City
2  CharLie   35  Chicago
3    David   40  Houston
4      Eva   45    Miani

In [ ]:
df = pd.read_csv("data.csv")

    Name  Age  Masks
0    Ram   21     90
1  Shyam   22     95
2   Hari   21     86

In [21]:
df[['Name', 'Age']]

      Name  Age
0     Arun   25
1      Bob   38
2  CharLie   35
3    David   40
4      Eva   45

In [26]:
df = pd.read_csv("data.csv")
df[['Name','Masks']]

    Name  Masks
0    Ram     90
1  Shyam     95
2   Hari     86

In [27]:
df.loc[1:2,['Age']]

   Age
1   22
2   21

In [28]:
df.iloc[0:2,0]

0      Ram
1    Shyam
Name: Name, dtype: object

In [29]:
df.loc[2:2,['Masks']]

   Masks
2     86

In [33]:
df.iloc[2:3,2]

2    86
Name: Masks, dtype: int64

In [38]:
df[df['Masks']>80 & (df['Age']>21)]

    Name  Age  Masks
0    Ram   21     90
1  Shyam   22     95
2   Hari   21     86

In [39]:
df['salary'] = [10000,30000,15000]

In [40]:
df

    Name  Age  Masks  salary
0    Ram   21     90   10000
1  Shyam   22     95   30000
2   Hari   21     86   15000

In [42]:
old_df

    Name  Age  Masks
0    Ram   21     90
1  Shyam   22     95
2   Hari   21     86

In [45]:
df[(df["salary"]==15000) & (df['Masks'] <90) & (df["Age"]<22)]

   Name  Age  Masks  salary
2  Hari   21     86   15000

In [49]:
df[['Age','Masks', 'salary']].median()

Age          21.0
Masks        90.0
salary    15000.0
dtype: float64

In [50]:
df[['Age','Masks', 'salary']].std()

Age           0.577350
Masks         4.509250
salary    10408.329997
dtype: float64

In [51]:
df[['Age','Masks', 'salary']].max()

Age          22
Masks        95
salary    30000
dtype: int64

In [52]:
df[['Age','Masks', 'salary']].min()

Age          21
Masks        86
salary    10000
dtype: int64

In [53]:
df[['Age','Masks', 'salary']].sum()

Age          64
Masks       271
salary    55000
dtype: int64

In [54]:
df[['Age','Masks', 'salary']].count()

Age       3
Masks     3
salary    3
dtype: int64

In [ ]:
import pandas as pd

data = {
    "name": []
}

In [ ]:
df.groupby('city')["name"].count()

<>:1: SyntaxWarning: str indices must be integers or slices, not str; perhaps you missed a comma?
<>:1: SyntaxWarning: str indices must be integers or slices, not str; perhaps you missed a comma?
C:\Users\Arun\AppData\Local\Temp\ipykernel_17156\2103978964.py:1: SyntaxWarning: str indices must be integers or slices, not str; perhaps you missed a comma?
  df.groupby('city'["salary"].mean())

NameError: name 'df' is not defined